### ISSUE TITLE
Missing constants on compile

### ISSUE THREAD

**Issue by bugproof** [shmuelyr/CaptainHook#4]
"JMP_TRAMPOLINE_LEN" is undefined	CaptainHook.cpp	93
"PG_HOOKTYPE_LEN" is undefined	 CaptainHook.cpp	128
"JMP_TRAMPOLINE_LEN" is undefined	CaptainHook.cpp	133

**Comment by shmuelyr** [comment]
hi, tnx for using in CaptainHook.
I just fixed it in the last commit.

**Comment by bugproof** [comment]
builds but can't link to it...
CaptainHook.lib(CaptainHook.obj) : error LNK2001: unresolved external symbol _g_uiVectorHandlerChainSize
1>CaptainHook.lib(CaptainHook.obj) : error LNK2001: unresolved external symbol _g_uiVectorHandlerMaxChainSize
1>CaptainHook.lib(CaptainHook.obj) : error LNK2001: unresolved external symbol _PageGuardExceptionManager
1>CaptainHook.lib(CaptainHook.obj) : error LNK2001: unresolved external symbol _g_VectorHandlerChain

to fix this add VectoredHandler.cpp to the project.

would be nice to add more hooking methods to this projects like IAT/EAT etc.

**Comment by shmuelyr** [comment]
hi, tnx.
i would add new methods, but i need more time (University and so on..).
if you want, you can pull request and i will merge it.

**Comment by shmuelyr** [comment]
Fix
